plugins {
    alias(libs.plugins.android.application)
    id 'com.google.gms.google-services'
}

android {
    namespace 'com.example.SGDDA'
    compileSdk 36

    defaultConfig {
        applicationId "com.example.SGDDA"
        minSdk 26
        targetSdk 36
        versionCode 1
        versionName "1.0"

        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_11
        targetCompatibility JavaVersion.VERSION_11
    }

    buildFeatures {
        viewBinding false
    }

    // --- CONFIGURAÇÃO CORRIGIDA PARA IGNORAR TESTES ---
    applicationVariants.all { variant ->
        if (variant.name == 'release') {

            // 1. TAREFA DO JAR
            project.tasks.register("exportJar${variant.name.capitalize()}", Jar) {
                from variant.javaCompileProvider.get().destinationDirectory
                archiveFileName.set("SGDDA_Executavel_${variant.name}.jar")
                destinationDirectory.set(file("$buildDir/outputs/jar"))
            }

            // 2. TAREFA DO JAVADOC (SÓ MAIN)
            task("gerarJavadoc", type: Javadoc) {
                description "Gera a documentação JavaDoc apenas para o código principal."

                // --- MUDANÇA IMPORTANTE: Pega só a pasta src/main/java ---
                source = android.sourceSets.main.java.srcDirs

                // Configura as bibliotecas (Android + Dependências do projeto)
                doFirst {
                    classpath = files(variant.javaCompileProvider.get().classpath.files) + files(android.bootClasspath)
                }

                options {
                    encoding "UTF-8"
                    charSet "UTF-8"
                    author true
                    version true
                    links "http://d.android.com/reference"
                }

                exclude '**/BuildConfig.java'
                exclude '**/R.java'
                failOnError false
                destinationDir = file("$buildDir/outputs/javadoc/")
            }
        }
    }
}

dependencies {
    implementation libs.appcompat
    implementation libs.material
    implementation libs.activity
    implementation libs.constraintlayout
    testImplementation libs.junit
    androidTestImplementation libs.ext.junit
    androidTestImplementation libs.espresso.core

    // Firebase
    implementation platform('com.google.firebase:firebase-bom:33.1.2')
    implementation 'com.google.firebase:firebase-auth'
    implementation 'com.google.firebase:firebase-firestore'

    // Gráficos
    implementation libs.mpandroidchart
}